apiVersion: v1
kind: Service
metadata:
  name: offeria-mcp-server
  labels:
    app: offeria-mcp-server
spec:
  type: ClusterIP

  selector:
    app: offeria-mcp-server

  ports:
    - name: http
      port: 8090
      targetPort: http
      protocol: TCP
